/*
 * generated by Xtext 2.14.0
 */
package uk.ac.lancaster.scc.turtles.stellar.lang.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class BSPLUiModule extends AbstractBSPLUiModule {
}
