/*
 * generated by Xtext 2.14.0
 */
package uk.ac.lancaster.scc.turtles.stellar.lang


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BSPLRuntimeModule extends AbstractBSPLRuntimeModule {
}
